version: 0.2
env:
  variables:
    AWS_ACCOUNT_ID: "305362906248"
    IMAGE_REPO_NAME: "ois-fetcher"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "eu-north-1"
  secrets-manager: empty
phases:
  build:
    commands:
      - echo "Minimal buildspec parsed and executed!"