version: 0.2

env:
  variables: # Standard environment variables
    AWS_ACCOUNT_ID: "305362906248"
    IMAGE_REPO_NAME: "ois-fetcher"
    IMAGE_TAG: "latest"
    AWS_DEFAULT_REGION: "eu-north-1"
    # These will be populated by the secrets-manager section below
    # We are just declaring them here.
    # DOCKERHUB_USER: "" # Optional declaration
    # DOCKERHUB_PASS: "" # Optional declaration
  secrets-manager:
    # These will populate DOCKERHUB_USERNAME and DOCKERHUB_PASSWORD directly
    # as environment variables available to the shell.
    DOCKERHUB_USERNAME: "DockerHubCredentials1:username"
    DOCKERHUB_PASSWORD: "DockerHubCredentials1:password"

phases:
  pre_build:
    commands:
      - echo "Attempting to log in to Docker Hub..."
      # For debugging, let's see if the variables are set AT ALL by the time this command runs
      - echo "Username from env: [$DOCKERHUB_USERNAME]"
      # - echo "Password from env: [$DOCKERHUB_PASSWORD]" # STILL BE CAUTIOUS WITH THIS
      # Ensure these exact variable names are used in docker login
      - docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_PASSWORD"
      - echo "Docker login command executed. Exit code: $?" # Check exit code
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - echo "ECR login command executed. Exit code: $?" # Check exit code
      - |
        aws ecr describe-repositories --repository-names $IMAGE_REPO_NAME --region $AWS_DEFAULT_REGION > /dev/null 2>&1 || \
        aws ecr create-repository --repository-name $IMAGE_REPO_NAME --region $AWS_DEFAULT_REGION --image-scanning-configuration scanOnPush=true --image-tag-mutability MUTABLE > /dev/null
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - echo Docker image pushed successfully.
